services:
  feedback-db:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - feedback-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: feedback-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      #KC_PROXY_HEADERS: xforwarded
      #KC_HOSTNAME: otziv-auth.mysubscription.digital
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - "8081:8080"
    depends_on:
      feedback-db:
        condition: service_healthy
    networks:
      - feedback-network

  gateway:
    build: .
    environment:
      GATEWAY_JWT_ISSUER_URI: http://keycloak:8080/realms/univerliga
      GATEWAY_AUTH_TOKEN_URL: http://keycloak:8080/realms/univerliga/protocol/openid-connect/token
      GATEWAY_MODE: mock
      ANALYTICS_BASE_URL: http://analytics:8080
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
    networks:
      - feedback-network


networks:
  feedback-network:
    name: feedback-network
    driver: bridge

    external: false
